#
# opencv_v4l2 - opencv_build_options.cmake file
#
# Copyright (c) 2017-2018, e-con Systems India Pvt. Ltd.  All rights reserved.
#

# Initial cache values for an optimized OpenCV 3.3.1 release build

set (BUILD_CUDA_STUBS          OFF CACHE BOOL "")
set (BUILD_DOCS                OFF CACHE BOOL "")
set (BUILD_EXAMPLES            OFF CACHE BOOL "")
set (BUILD_IPP_IW              OFF CACHE BOOL "")
set (BUILD_ITT                 OFF CACHE BOOL "")
set (BUILD_JASPER              ON  CACHE BOOL "")
set (BUILD_JPEG                ON  CACHE BOOL "")
set (BUILD_OPENEXR             ON  CACHE BOOL "")
set (BUILD_PACKAGE             OFF CACHE BOOL "")
set (BUILD_PERF_TESTS          OFF CACHE BOOL "")
set (BUILD_PNG                 ON  CACHE BOOL "")
set (BUILD_PROTOBUF            ON  CACHE BOOL "")
set (BUILD_SHARED_LIBS         ON  CACHE BOOL "")
set (BUILD_TBB                 ON  CACHE BOOL "")
set (BUILD_TIFF                ON  CACHE BOOL "")
set (BUILD_TESTS               OFF CACHE BOOL "")
set (BUILD_WEBP                ON  CACHE BOOL "")
set (BUILD_WITH_DEBUG_INFO     OFF CACHE BOOL "")
set (BUILD_WITH_DYNAMIC_IPP    OFF CACHE BOOL "")
set (BUILD_ZLIB                ON  CACHE BOOL "")
set (CMAKE_BUILD_TYPE          "Release" CACHE STRING "")
set (CUDA_BUILD_EMULATION      OFF CACHE BOOL "")
set (CUDA_FAST_MATH            ON  CACHE BOOL "")
# set (CUDA_HOST_COMPILER        "/usr/bin/g++" CACHE STRING "To overcome bad interaction between ccache and nvcc in older cmake versions")
set (CUDA_PROPAGATE_HOST_FLAGS ON  CACHE BOOL "")
set (CV_DISABLE_OPTIMIZATION   OFF CACHE BOOL "")
set (CV_ENABLE_INTRINSICS      ON  CACHE BOOL "")
set (CV_TRACE                  OFF CACHE BOOL "")
set (ENABLE_BUILD_HARDENING    ON  CACHE BOOL "")
# set (ENABLE_CCACHE             ON  CACHE BOOL "")
set (ENABLE_COVERAGE           OFF CACHE BOOL "")
set (ENABLE_CXX11              ON  CACHE BOOL "") # RE-CHECK
set (ENABLE_FAST_MATH          ON  CACHE BOOL "")
set (ENABLE_GNU_STL_DEBUG      OFF CACHE BOOL "")
set (ENABLE_IMPL_COLLECTION    OFF CACHE BOOL "")
set (ENABLE_INSTRUMENTATION    OFF CACHE BOOL "")
set (ENABLE_OMIT_FRAME_POINTER ON  CACHE BOOL "")
set (ENABLE_PROFILING          OFF CACHE BOOL "")
set (ENABLE_PYLINT             OFF CACHE BOOL "")
set (INSTALL_C_EXAMPLES        OFF CACHE BOOL "")
set (INSTALL_PYTHON_EXAMPLES   OFF CACHE BOOL "")
set (INSTALL_TESTS             OFF CACHE BOOL "")
set (WITH_CUBLAS               ON  CACHE BOOL "")
set (WITH_CUDA                 ON  CACHE BOOL "")
set (WITH_CUFFT                ON  CACHE BOOL "")
set (WITH_EIGEN                ON  CACHE BOOL "")
set (WITH_GSTREAMER            ON  CACHE BOOL "")
set (WITH_GTK                  ON  CACHE BOOL "")
set (WITH_GTK_2_X              ON  CACHE BOOL "")
set (WITH_IPP                  OFF CACHE BOOL "")
set (WITH_ITT                  OFF CACHE BOOL "")
set (WITH_JASPER               ON  CACHE BOOL "")
set (WITH_JPEG                 ON  CACHE BOOL "")
set (WITH_LAPACK               ON  CACHE BOOL "")
set (WITH_LIBV4L               OFF CACHE BOOL "")
set (WITH_NVCUVID              OFF CACHE BOOL "")
set (WITH_OPENEXR              ON  CACHE BOOL "")
set (WITH_OPENGL               ON  CACHE BOOL "")
set (WITH_OPENMP               ON  CACHE BOOL "")
set (WITH_PNG                  ON  CACHE BOOL "")
set (WITH_PTHREADS_PF          ON  CACHE BOOL "")
set (WITH_QT                   OFF CACHE BOOL "FIXME: Installing Qt dependency results in build failure due to linking error. Workaround to be explored.")
set (WITH_TBB                  ON  CACHE BOOL "")
set (WITH_TIFF                 ON  CACHE BOOL "")
set (WITH_V4L                  ON  CACHE BOOL "")
set (WITH_WEBP                 ON  CACHE BOOL "")
